config/routes.rb
Multitenant::Application.routes.draw do
  namespace :system do
    resources :clients do
      member do
        post :create_database
        post :migrate_database
        post :drop_database
      end
    end
    resources :databases
  end

  resources :dummy
end

app/models/system.rb
module System
  def self.table_name_prefix
    'system_'
  end
end

app/models/system/client.rb
class System::Client < ActiveRecord::Base
  validates :name, :presence => true, :length => {:maximum => 30}
  validates :domain, :presence => true, :length => {:minimum => 4, :maximum => 12}, :format => /\A[a-z]{4,12}\Z/
  validates :status, :presence => true

  belongs_to :database

  def initialize(*args)
    super *args
    self.status = 'initial'
  end

  def create_database
    return unless %w(initial dropped).include? self.status
    database.create_database database_name
    self.status = 'created'
    save
  end

  def migrate_database
    return unless %w(created migrated).include? self.status
    database.migrate_database database_name
    self.status = 'migrated'
    save
  end

  def drop_database
    return unless %w(created migrated).include? self.status
    database.drop_database database_name
    self.status = 'dropped'
    save
  end

  def database_name
    "#{self.connection.current_database}_#{domain}"
  end

  def proc_client(&block)
    return unless block_given?
    db = self.database
    query_cache_enabled = System::ClientBase.connection.query_cache_enabled
    System::ClientBase.establish_connection({:adapter => 'postgresql',
                                              :encoding => 'unicode',
                                              :database => database_name,
                                              :hostname => db.hostname,
                                              :port => db.port,
                                              :username => db.username,
                                              :password => db.password
                                            })
    sync_query_cache_state(query_cache_enabled)
    yield
  ensure
    System::ClientBase.establish_connection
    sync_query_cache_state(query_cache_enabled)
  end

  private

  # connection を張りなおすので query_cache の設定を再設定する
  def sync_query_cache_state(query_cache_enabled)
    if query_cache_enabled
      System::ClientBase.connection.enable_query_cache!
    else
      System::ClientBase.connection.disable_query_cache!
    end
  end

end

app/models/system/client_base.rb
class System::ClientBase < ActiveRecord::Base
  self.abstract_class = true
end

app/models/system/database.rb
class System::Database < ActiveRecord::Base
  validates :name, :presence => true, :length => {:maximum => 30}
  validates :hostname, :presence => true, :length => {:maximum => 30}
  validates :port, :presence => true
  validates :username, :presence => true, :format => /\A[a-z]{4,12}\Z/

  def create_database(database_name)
    proc_database do
      self.class.connection.create_database database_name
    end
  end

  def drop_database(database_name)
    proc_database do
      self.class.connection.drop_database database_name
    end
  end

  def migrate_database(database_name, target_version = nil)
    proc_database(database_name) do
      ActiveRecord::Migrator.migrate("db/client_migrate", target_version)
    end
  end

  def proc_database(database_name = 'template1', &block)
    ActiveRecord::Base.establish_connection({:adapter => 'postgresql',
                                              :encoding => 'unicode',
                                              :database => database_name,
                                              :hostname => hostname,
                                              :port => port,
                                              :username => username,
                                              :password => password
                                            })
    yield
  ensure
    ActiveRecord::Base.establish_connection
  end
end

app/controllers/system/clients_controller.rb
class System::ClientsController < ApplicationController
  # GET /system/clients
  # GET /system/clients.xml
  def index
    @system_clients = System::Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @system_clients }
    end
  end

  # GET /system/clients/1
  # GET /system/clients/1.xml
  def show
    @system_client = System::Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @system_client }
    end
  end

  # GET /system/clients/new
  # GET /system/clients/new.xml
  def new
    @system_client = System::Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @system_client }
    end
  end

  # GET /system/clients/1/edit
  def edit
    @system_client = System::Client.find(params[:id])
  end

  # POST /system/clients
  # POST /system/clients.xml
  def create
    @system_client = System::Client.new(params[:system_client])

    respond_to do |format|
      if @system_client.save
        format.html { redirect_to(@system_client, :notice => 'Client was successfully created.') }
        format.xml  { render :xml => @system_client, :status => :created, :location => @system_client }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @system_client.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /system/clients/1
  # PUT /system/clients/1.xml
  def update
    @system_client = System::Client.find(params[:id])

    respond_to do |format|
      if @system_client.update_attributes(params[:system_client])
        format.html { redirect_to(@system_client, :notice => 'Client was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @system_client.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /system/clients/1
  # DELETE /system/clients/1.xml
  def destroy
    @system_client = System::Client.find(params[:id])
    @system_client.destroy

    respond_to do |format|
      format.html { redirect_to(system_clients_url) }
      format.xml  { head :ok }
    end
  end

  def create_database
    @system_client = System::Client.find(params[:id])

    respond_to do |format|
      if @system_client.create_database
        format.html { redirect_to(system_clients_url, :notice => 'Client Database was successfully created.') }
        format.xml  { head :ok }
      else
        format.html { redirect_to(system_clients_url, :notice => 'Client Database was already created.') }
        format.xml  { render :xml => @system_client.errors, :status => :unprocessable_entity }
      end
    end
  end

  def migrate_database
    @system_client = System::Client.find(params[:id])

    respond_to do |format|
      if @system_client.migrate_database
        format.html { redirect_to(system_clients_url, :notice => 'Client Database was successfully migrated.') }
        format.xml  { head :ok }
      else
        format.html { redirect_to(system_clients_url, :notice => 'Client Database was already migrated.') }
        format.xml  { render :xml => @system_client.errors, :status => :unprocessable_entity }
      end
    end
  end

  def drop_database
    @system_client = System::Client.find(params[:id])

    respond_to do |format|
      if @system_client.drop_database
        format.html { redirect_to(system_clients_url, :notice => 'Client Database was successfully dropped.') }
        format.xml  { head :ok }
      else
        format.html { redirect_to(system_clients_url, :notice => 'Client Database was already dropped.') }
        format.xml  { render :xml => @system_client.errors, :status => :unprocessable_entity }
      end
    end
  end

end

app/controllers/system/databases_controller.rb
class System::DatabasesController < ApplicationController
  # GET /system/databases
  # GET /system/databases.xml
  def index
    @system_databases = System::Database.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @system_databases }
    end
  end

  # GET /system/databases/1
  # GET /system/databases/1.xml
  def show
    @system_database = System::Database.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @system_database }
    end
  end

  # GET /system/databases/new
  # GET /system/databases/new.xml
  def new
    @system_database = System::Database.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @system_database }
    end
  end

  # GET /system/databases/1/edit
  def edit
    @system_database = System::Database.find(params[:id])
  end

  # POST /system/databases
  # POST /system/databases.xml
  def create
    @system_database = System::Database.new(params[:system_database])

    respond_to do |format|
      if @system_database.save
        format.html { redirect_to(@system_database, :notice => 'Database was successfully created.') }
        format.xml  { render :xml => @system_database, :status => :created, :location => @system_database }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @system_database.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /system/databases/1
  # PUT /system/databases/1.xml
  def update
    @system_database = System::Database.find(params[:id])

    respond_to do |format|
      if @system_database.update_attributes(params[:system_database])
        format.html { redirect_to(@system_database, :notice => 'Database was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @system_database.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /system/databases/1
  # DELETE /system/databases/1.xml
  def destroy
    @system_database = System::Database.find(params[:id])
    @system_database.destroy

    respond_to do |format|
      format.html { redirect_to(system_databases_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/system/clients_helper.rb
module System::ClientsHelper
end

app/helpers/system/databases_helper.rb
module System::DatabasesHelper
end

app/views/system/databases/_form.html.erb
<%= form_for(@system_database) do |f| %>
  <% if @system_database.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@system_database.errors.count, "error") %> prohibited this system_database from being saved:</h2>

      <ul>
      <% @system_database.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hostname %><br />
    <%= f.text_field :hostname %>
  </div>
  <div class="field">
    <%= f.label :port %><br />
    <%= f.text_field :port %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/system/databases/edit.html.erb
<h1>Editing system_database</h1>

<%= render 'form' %>

<%= link_to 'Show', @system_database %> |
<%= link_to 'Back', system_databases_path %>

app/views/system/databases/index.html.erb
<h1>Listing system_databases</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Hostname</th>
    <th>Port</th>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @system_databases.each do |system_database| %>
  <tr>
    <td><%= system_database.name %></td>
    <td><%= system_database.hostname %></td>
    <td><%= system_database.port %></td>
    <td><%= system_database.username %></td>
    <td><%= system_database.password %></td>
    <td><%= link_to 'Show', system_database %></td>
    <td><%= link_to 'Edit', edit_system_database_path(system_database) %></td>
    <td><%= link_to 'Destroy', system_database, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Database', new_system_database_path %>

app/views/system/databases/new.html.erb
<h1>New system_database</h1>

<%= render 'form' %>

<%= link_to 'Back', system_databases_path %>

app/views/system/databases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @system_database.name %>
</p>

<p>
  <b>Host:</b>
  <%= @system_database.hostname %>
</p>

<p>
  <b>Port:</b>
  <%= @system_database.port %>
</p>

<p>
  <b>Port:</b>
  <%= @system_database.username %>
</p>

<p>
  <b>Port:</b>
  <%= @system_database.password %>
</p>


<%= link_to 'Edit', edit_system_database_path(@system_database) %> |
<%= link_to 'Back', system_databases_path %>